### ISSUE TITLE
Non-zero exit status produced by subprocess when compiling dashboard_yew

### ISSUE THREAD

**Issue by ex0dus-0x** [kryptco/sigchain#3]
Currently on __Arch Linux x86_64__, so am building this manually:
```
Linux ex0dus 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
```
The error was produced by `dashboard_yew` when running `make`.
```
$ cd $GOPATH/src/github.com/kryptco/kr
$ make
rm -rf bin lib Frameworks
mkdir -p bin
mkdir -p lib
mkdir -p Frameworks
go clean -cache || true
cd sigchain && CARGO_RELEASE=--release make libsigchain-with-dashboard
make[1]: Entering directory '/home/ex0dus/go/src/github.com/kryptco/kr/sigchain'
if [ "`cargo web --version`" != "cargo-web 0.6.10" ]; then echo "Please install cargo-web 0.6.10 with \`cargo install -f --version 0.6.10 cargo-web\`"; exit 1; fi
# use rsync so that file modifed times are only updated when the contents change
cd dashboard_yew && cargo web deploy --release --target=wasm32-unknown-emscripten && rsync --checksum --delete -r ../target/deploy/* ../target/deploy-final
   Compiling dashboard_yew v0.1.0 (file:///home/ex0dus/go/src/github.com/kryptco/kr/sigchain/dashboard_yew)
error: linking with `emcc` failed: exit code: 1
  |
  = note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew0-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew1-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew10-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew11-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew12-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew13-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew14-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew15-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew2-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew3-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew4-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew5-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew6-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew7-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew8-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew9-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "-o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.crate.allocator.rcgu.o" "-O3" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps" "-L" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/release/deps" "-L" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsigchain_core-6128ab6fb883c9ce.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libcrc24-80b5409e3f745bc6.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsemver-3ccbc058d4b91fcb.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsemver_parser-604f9831eb15d30f.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsha1-9cd2a8e0d35ed64e.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liburl-45257cbb10fdb613.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libpercent_encoding-7d6c778e0dd0129c.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libidna-f3af5d9aa9d97bfe.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libunicode_normalization-4ef45b5f24f63662.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libunicode_bidi-c2ce2a088d084422.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libmatches-11167115c8d4d786.rlib" "/hom= note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew0-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew1-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew10-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew11-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew12-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew13-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew14-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew15-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew2-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew3-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew4-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew5-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew6-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew7-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew8-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.dashboard_yew9-eb73b18fb3a45498d3cedea29dcb2b1a.rs.rcgu.o" "-o" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/dashboard_yew.crate.allocator.rcgu.o" "-O3" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps" "-L" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/release/deps" "-L" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsigchain_core-6128ab6fb883c9ce.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libcrc24-80b5409e3f745bc6.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsemver-3ccbc058d4b91fcb.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsemver_parser-604f9831eb15d30f.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsha1-9cd2a8e0d35ed64e.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liburl-45257cbb10fdb613.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libpercent_encoding-7d6c778e0dd0129c.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libidna-f3af5d9aa9d97bfe.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libunicode_normalization-4ef45b5f24f63662.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libunicode_bidi-c2ce2a088d084422.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libmatches-11167115c8d4d786.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libscopeguard-e6be46da5dcc32e5.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liblog-859c6507c62610ed.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liblog-cfed7e78228609ce.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liberror_chain-61555983a97d2af0.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libdotenv-f1d5e0e1f0ca2789.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libregex-58365e4ef6f95c21.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libutf8_ranges-3d32d1fa3c9ef942.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libregex_syntax-5bd0bd30c7af6f16.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libthread_local-7465cf0fb718a57b.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libunreachable-89321d23d82ba816.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libvoid-7b798ccf19271ef6.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libaho_corasick-0dd208f60bf064a2.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/targee/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libscopeguard-e6be46da5dcc32e5.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liblog-859c6507c62610ed.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liblog-cfed7e78228609ce.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liberror_chain-61555983a97d2af0.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libdotenv-f1d5e0e1f0ca2789.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libregex-58365e4ef6f95c21.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libutf8_ranges-3d32d1fa3c9ef942.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libregex_syntax-5bd0bd30c7af6f16.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libthread_local-7465cf0fb718a57b.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libunreachable-89321d23d82ba816.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libvoid-7b798ccf19271ef6.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libaho_corasick-0dd208f60bf064a2.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libmemchr-d1b6ace49c937727.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liberror_chain-12c6bbe6dba94c2e.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libbacktrace-edea748a77db7f03.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/librustc_demangle-0a090b9472a0b5cb.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libcfg_if-cc454cceab8757f4.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liblazy_static-fe293aa56d0be1cc.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libbase64-f349b4c4eeec6d92.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libsafemem-dfd28b5e73d24548.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libchrono-a96e4fcfc21c943a.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libnum-1ca22e255507d6f6.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libnum_iter-ea84123dbf3779c8.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libnum_integer-80e0f6fd55857f99.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libtime-969111a5e90c74b9.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libyew-8e451c4bd34d5dcd.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libstdweb-c58b3ffcdf8c7a21.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libserde_json-2e6cceba6c3b39ae.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libdtoa-004810f074d411ca.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libitoa-4bf80629a3585bed.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libnum_traits-d73362ef5190a630.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libserde-28af2328d7bf7ae6.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libhttp-6787e30854d306a0.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libfnv-5492da5b13108dbf.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libbytes-1996e1de0ecf824e.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libiovec-35c0d988fa206532.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/liblibc-c9ff494e22da7f50.rlib" "/home/ex0dus/go/src/github.com/kryptco/kr/sigchain/target/wasm32-unknown-emscripten/release/deps/libbyteorder-09041bedad674db1.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libstd-ef7937aa466c802c.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libpanic_unwind-4ba159a9f2c9f1ba.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libunwind-3d00844ddab056a3.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc_system-c4ff320ecd816bed.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liblibc-09f26fd73198909a.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc-1148e50ab6df501b.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcore-c9a183cdf4b5470a.rlib" "/home/ex0dus/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/libcompiler_builtins-110dd325afea7b8b.rlib" "-l" "c" "-s" "NO_EXIT_RUNTIME=1" "-s" "ALLOW_MEMORY_GROWTH=1" "-s" "BINARYEN=1" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
  = note: INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/home/ex0dus/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
          opt: Unknown command line argument '-vectorize-slp-aggressive=false'.  Try: '/opt/emsdk/clang/e1.38.6_64bit/opt -help'
          opt: Did you mean '-vectorize-num-stores-pred=false'?
          Traceback (most recent call last):
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc", line 13, in <module>
              emcc.run()
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc.py", line 1394, in run
              shared.Building.llvm_opt(temp_file, options.llvm_opts, new_temp_file)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/shared.py", line 1953, in llvm_opt
              proc = run_process([LLVM_OPT] + inputs + opts + ['-o', target], stdout=PIPE)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/shared.py", line 223, in run_process
              return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/shared.py", line 219, in run_base
              result.check_returncode()
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/shared.py", line 206, in check_returncode
              raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
          tools.shared.Py2CalledProcessError: Command '['/opt/emsdk/clang/e1.38.6_64bit/opt', '/tmp/tmpyauUOa/dlmalloc.bc', '-O3', '-disable-loop-vectorization', '-disable-slp-vectorization', '-vectorize-loops=false', '-vectorize-slp=false', '-vectorize-slp-aggressive=false', '-o', '/tmp/tmpIm5zT5/dlmalloc_0.o']' returned non-zero exit status 1
          ERROR:root:'/usr/bin/python2 /home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc /home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/system/lib/dlmalloc.c -o /tmp/tmpyauUOa/dlmalloc.bc -O2' failed
          Traceback (most recent call last):
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc.py", line 2754, in <module>
              run()
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc.py", line 1455, in run
              extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout_=None, stderr_=None, forced=forced_stdlibs)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/system_libs.py", line 499, in calculate
              libfile = shared.Cache.get(name, do_create, extension=suffix)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/cache.py", line 101, in get
              temp = creator()
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/system_libs.py", line 497, in do_create
              ret = create(name)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/system_libs.py", line 314, in create_dlmalloc
              check_call([shared.PYTHON, shared.EMCC, shared.path_from_root('system', 'lib', 'dlmalloc.c'), '-o', o] + cflags)
            File "/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/shared.py", line 247, in check_call
              subprocess.check_call(cmd, *args, **kw)
            File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['/usr/bin/python2', '/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc', '/home/ex0dus/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/system/lib/dlmalloc.c', '-o', '/tmp/tmpyauUOa/dlmalloc.bc', '-O2']' returned non-zero exit status 1
          

error: aborting due to previous error
error: Could not compile `dashboard_yew`.

To learn more, run the command again with --verbose.
error: build failed
make[1]: *** [Makefile:25: libsigchain-with-dashboard] Error 101
make[1]: Leaving directory '/home/ex0dus/go/src/github.com/kryptco/kr/sigchain'
make: *** [Makefile:71: all] Error 2
```

Not entirely if this is a problem with `sigchain` or my own `emscripten` installation. As you can tell, `cargo-web` is at its optimal version for compilation and I have `nightly` set as default with `rustup`.

Let me know what you think!

**Comment by kcking** [comment]
My guess would be an issue with your `~/.emscripten`, can you try moving it to `~/.emscripten.bak` and see if the defaults work?

**Comment by ex0dus-0x** [comment]
Works great! Thanks!
